name: PROD - Dependency Track
on:
  workflow_call:

  workflow_dispatch:

jobs:
  sbom:
    name: Upload SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_call' && github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a accepted branch"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          scan-type: fs
          scan-ref: "package-lock.json"
          format: cyclonedx
          output: sbom.json

      - name: Upload SBOM
        env:
          X_API_KEY: ${{ secrets.DTRACK_X_API_KEY_PROD }}
          PROJECT_ID: d70a640f-0188-4e84-a0ba-0acc3015ff5a
        run: |
          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" \
            -X "POST" "https://api-dependencytrack.cloudtotvs.com.br/api/v1/bom" \
            -H 'Content-Type: multipart/form-data' \
            -H "X-Api-Key: $X_API_KEY" \
            -F "project=$PROJECT_ID" \
            -F "bom=@sbom.json")

          if [ $HTTP_STATUS != "200" ]; then
            echo "Failed to upload SBOM. HTTP STATUS: $HTTP_STATUS"
            echo "API Response:"
            if [ -f response.json ]; then
              cat response.json
            else
              echo "No response body captured (response.json not found)."
            fi
            rm -f response.json
            exit 1;
          fi

          # Clean up temporary response file
          rm -f response.json
