name: DEV - DTrack

on:
  push:
    branches:
      - "development"
    paths:
      - ".github/workflows/dependency_track_dev.yml"
      - "src/**"
      - "package-lock.json"

permissions:
  id-token: write
  contents: read

jobs:
  dependency_track:
    name: Deploy artifact to Dependency Track
    uses: totvscloud-seginf/shared-workflows/.github/workflows/dependency-track.yml@v1.9.6
    secrets:
      dtrack_x_api_key: ${{ secrets.DTRACK_X_API_KEY_PROD }}
    with:
      project_id: 6246bc56-99f8-4f18-b35c-7a806bae54a0
      build_container: false
      build_submodules: false
      scan_ref: "package-lock.json"
      scan_type: fs
