name: PROD - DTrack

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/dependency_track_prod.yml"
      - "src/**"
      - "package-lock.json"
# deploy
permissions:
  id-token: write
  contents: read

jobs:
  dependency_track:
    name: Deploy artifact to Dependency Track
    uses: totvscloud-seginf/shared-workflows/.github/workflows/dependency-track.yml@feat/parameterize_runs_on
    secrets:
      dtrack_x_api_key: ${{ secrets.DTRACK_X_API_KEY_PROD }}
    with:
      project_id: d70a640f-0188-4e84-a0ba-0acc3015ff5a
      build_container: false
      build_submodules: false
      scan_ref: "package-lock.json"
      scan_type: fs
      runs_on: ubuntu-latest
